language: go
sudo: false

matrix:
  include:
    - go: 1.11.x
    - go: 1.12.x
    - go: 1.13.x
    - go: tip
  allow_failures:
    - go: tip

env:
  - GO111MODULE=on

install:
  - go get -t -v ./...
  - go get github.com/mattn/goveralls
  - go get github.com/go-playground/overalls
  - go install github.com/go-playground/overalls

script:
  - diff -u <(echo -n) <(gofmt -d .)
  - go test -v -race ./...
  - overalls -project=github.com/usmanhalalit/gost  -covermode=count
  - $HOME/gopath/bin/goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken=$COVERALLS_TOKEN